package com.spenderman.Observer.EvenEnum;

public enum EnEvenType {
    THEME_CHANGED,
    TRANSACTION_ADDED,
    TRANSACTION_UPDATED,
    TRANSACTION_DELETED,
    WALLET_ADDED,
    WALLET_UPDATED,
    WALLET_DELETED,
    CATEGORY_ADDED,
    CATEGORY_UPDATED,
    CATEGORY_DELETED,
    GOAL_ADDED,
    GOAL_UPDATED,
    GOAL_DELETED,
    CYCLE_ADDED,
    CYCLE_UPDATED,
    CYCLE_DELETED,
    PASSWORD_CHANGED
}
